favicon = "images/favicon.ico"
logo = "images/logo.png"
logo_darkmode = "images/logo-darkmode.png"
logo_width = "160px"
logo_height = "32px"
logo_webp = true
logo_text = "Mathlads"
navbar_fixed = true

theme_switcher = true
theme_default = "system"

mainSections = ["blog"]

contact_form_action = "#"

google_tag_manager = "GTM-MLVSGF54"
google_adsense = ""

custom_script = ""

copyright = "Authored by [Headache Group](https://github.com/orgs/Headache-Group). Theme by [Zeon Studio](https://zeon.studio)."

[preloader]
enable = false
preloader = ""

[navigation_button]
enable = true
label = "get a quote"
link = "contact"

[search]
enable = true
primary_color = "#121212"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true

[metadata]
keywords = ["Mathematics", "AI"]
description = "Mathematics - Base and beauty"
author = "Headache group"
image = "images/og-image.png"


[site_verification]
google = "google50a5c49ae8460468"
facebook = "" # Your verification code

[cookies]
enable = false
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

[mermaid]
js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'

[widgets]
sidebar = ["categories", "tags"]


[subscription]
enable = false
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"
